### ISSUE TITLE
Doesn't work with hotkeys. 

### ISSUE THREAD

**Issue by mzso** [vovcacik/bug-566510-firefox-addon#3]
It seems like hotkeys always work on one tab. Which is a problem, because I have all the common stuff removed from the context menu since (with Menu Editor) I never forget the hotkeys for them I don't need them in the context menu.
For example <kbd>ctrl+w/ctrl+f4, f5/ctrl+f5</kbd>

**Comment by vovcacik** [comment]
This one bothers me too. However I want this addon to be future compatible with Firefox so I need to follow their [guidelines](https://wiki.mozilla.org/Firefox/Projects/Tab_Multi-Selection/Design) on tab multi-selection and it states:

> There are no (non-mouse) keyboard shortcuts planned to handle multiple tab selection.

**Comment by mzso** [comment]
I understand. To bad...
