### ISSUE TITLE
I don't get bold context menu items.

### ISSUE THREAD

**Issue by mzso** [vovcacik/bug-566510-firefox-addon#4]
I don't get the bold context menu items. I also have a lot of them removed (#3), but the one that (close other tabs) remains isn't bold and doesn't work, all but one tab is closed.
Now TMP incompatiblility is claimed to be fixed, should I look for something else? I don't think I have anything else that directly effects tab functioning.

PS: Close other tabs works on a clean profile but I still get a notification claiming that I close n-1 tabs regardless of whatever tabs are actually closed.

**Comment by vovcacik** [comment]
This menu item was a conflict between this addon and TMP and the conflict was resolved in favour of TMP, so "Close Other Tabs" is not supporting multiselection nor is bold when you have TMP installed. [Source reference](https://github.com/vovcacik/bug-566510-firefox-addon/blob/master/chrome/content/compatibility/compatibility.js#L15).

You should however see all the other supported commands to be bold when you enable them again, right? Also see #5 for the warning issue.

**Comment by vovcacik** [comment]
This bug report describes expected behaviour.
