### ISSUE TITLE
Context Menu (right-click on tab) is blank

### ISSUE THREAD

**Issue by ADTC** [vovcacik/bug-566510-firefox-addon#7]
Context menu is blank, as shown in screenshot. Firefox 47 and a couple of earlier versions as well.

![Screenshot](https://cloud.githubusercontent.com/assets/6047296/16029565/2d686c4a-321c-11e6-90ad-627cb39961d8.png)

**Comment by vovcacik** [comment]
Hi, thanks for report. I have noticed this as well. But as the Firefox is dropping support for XUL addons (as this one) I am archiving this repo.
