### ISSUE TITLE
Does not work with Tab Center add-on

### ISSUE THREAD

**Issue by Keith94** [vovcacik/bug-566510-firefox-addon#8]
https://testpilot.firefox.com/experiments/tab-center/

If tabs are displayed vertically with this add-on, multi select function does not work anymore. However, multi select add-on is very much needed when dealing with lots of tabs like in this case. Please find a fix for it.

**Comment by vovcacik** [comment]
I had this tested with the vertical tab addon called *Tree Style Tab*, but it is possible there is some conflict between this and *Tab Center*.

However Firefox has dropped support for XUL addons, so I am archiving this repo.
